"""1 migration

Revision ID: 8ecb77cbcc7c
Revises: 
Create Date: 2023-08-02 13:58:26.599117

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8ecb77cbcc7c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chatid',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('chat_id', sa.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('chat_id')
    )
    op.create_table('projects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_in_work_composer', sa.TEXT(), nullable=True),
    sa.Column('title', sa.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id_in_work_composer')
    )
    op.create_table('projectssite',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('is_complite', sa.Boolean(), nullable=True),
    sa.Column('row', sa.TEXT(), nullable=True),
    sa.Column('project', sa.TEXT(), nullable=True),
    sa.Column('create_project', sa.TEXT(), nullable=True),
    sa.Column('parsing', sa.TEXT(), nullable=True),
    sa.Column('verstka', sa.TEXT(), nullable=True),
    sa.Column('buy_domain', sa.TEXT(), nullable=True),
    sa.Column('deploy', sa.TEXT(), nullable=True),
    sa.Column('content', sa.TEXT(), nullable=True),
    sa.Column('acquiring', sa.TEXT(), nullable=True),
    sa.Column('release', sa.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_in_work_composer', sa.TEXT(), nullable=True),
    sa.Column('id_projects', sa.TEXT(), nullable=True),
    sa.Column('id_users', sa.TEXT(), nullable=True),
    sa.Column('title', sa.TEXT(), nullable=True),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('author', sa.TEXT(), nullable=True),
    sa.Column('status', sa.TEXT(), nullable=True),
    sa.Column('id_project_site', sa.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id_in_work_composer')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_in_work_composer', sa.TEXT(), nullable=True),
    sa.Column('fio', sa.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id_in_work_composer')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    op.drop_table('tasks')
    op.drop_table('projectssite')
    op.drop_table('projects')
    op.drop_table('chatid')
    # ### end Alembic commands ###
